#### General information about the project    ####
#### All this will be visible on DataCamp.com ####
title          : "The title of the project"
description    : >
  A short description of the project, less than 140 characters.
long_description: |
  A longer description of the project around 3 - 4 lines. 
  Should mention and link to prerequsite courses.
time_needed: "45 minutes" # "30/45/60 minutes".
instructors: # DataCamp connected email of the creator of the Project
  - rasmus@datacamp.com
collaborators: # DataCamp connected email of people that helped with teh Project
  - rasmus@datacamp.com

#### Metadata regarding course requirements and topics ####
#### This will be updated by your DataCamp contact     ####
technology: 1 # 1 == R, 2 == python, 3 == sql
# IDs for courses that are prerequisites
# See https://mb.datacamp.com/question/126 for IDs
prerequisites: 
  - 1498 # Data Visualization in R
difficulty_level: 2 # 1 == easy, 2 == medium, 3 == hard
# IDs for the topics the project covers
# See https://mb.datacamp.com/question/319 for IDs
topics:
  - 12
# A link to the cover illustration of the project.
illustration: "https://s3.amazonaws.com/assets.datacamp.com/production/project_37/datasets/project_image.png"

#### Technical settings for the docker image running the project ####
#### This will be updated by your DataCamp contact.              ####
language       : r # One of r, python or sql
# The name of the docker image used to run the course
from           : 'r-notebooks-prod:21'
runtime_config : default # default/heavy . Set to heavy for more resource intensive projects.

#### Set this flag to live preleases the Project on DataCamp.                ####
#### Please don't do this without talking with your DataCamp contact first.  ####
state          : development # development/live .

